@ContactApp_HostAddress = https://localhost:7111



POST {{ContactApp_HostAddress}}/api/contact/CreateContact
Content-Type: application/json

{
  "name": "John Doe",
  "isActive": 1,
  "createdUserId": 2
}

###

POST {{ContactApp_HostAddress}}/api/contact/EditContact
Content-Type: application/json

{
  "id": 1,
  "name": "Joe John",
  "isActive": 1,
  "editedUserId": 1
}

###

POST {{ContactApp_HostAddress}}/api/contactdetail/CreateContactDetail
Content-Type: application/json

{
  "contactId": 2,
  "contactNumber": "9123456788",
  "createdUserId": 2
}

###

POST {{ContactApp_HostAddress}}/api/contactdetail/EditContactDetail
Content-Type: application/json

{
  "id": 6,
  "contactId": 4,
  "contactNumber": "9999999999",
  "editedUserId": 1
}

###

POST {{ContactApp_HostAddress}}/api/contact/CreateContactWithDetails
Content-Type: application/json

{
  "name": "Alex",
  "isActive": 1,
  "createdUserId": 2,
  "contactDetails": [
    {
      "contactNumber": "9284653712",
      "createdUserId": 2
    },
    {
      "contactNumber": "9756384957",
      "createdUserId": 2
    }
  ]
}

###

@id=4
GET {{ContactApp_HostAddress}}/api/contact/GetContactById/{{id}}

###

GET {{ContactApp_HostAddress}}/api/contactdetail/GetContactDetailById/{{id}}

###

GET {{ContactApp_HostAddress}}/api/contact/GetContactAndDetailsById/{{id}}

###

PUT {{ContactApp_HostAddress}}/api/contact/UnblockContact/{{id}}

###

PUT {{ContactApp_HostAddress}}/api/contact/DeleteContact/{{id}}

###

PUT {{ContactApp_HostAddress}}/api/contact/BlockContact/{{id}}

###
