<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ContactApp.Framework\ContactApp.Framework.csproj" />
    <ProjectReference Include="..\ContactApp.DTOs\ContactApp.DTOs.csproj" />
    <ProjectReference Include="..\ContactMS.Data.Contract\ContactMS.Data.Contract.csproj" />
    <ProjectReference Include="..\ContactMS.Data\ContactApp.Data.csproj" />
  </ItemGroup>

</Project>
